//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlcvDemo2.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastModel1Path
        {
            get
            {
                return ((string)(this["LastModel1Path"]));
            }
            set
            {
                this["LastModel1Path"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastModel2Path
        {
            get
            {
                return ((string)(this["LastModel2Path"]));
            }
            set
            {
                this["LastModel2Path"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastImagePath
        {
            get
            {
                return ((string)(this["LastImagePath"]));
            }
            set
            {
                this["LastImagePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2560")]
        public int SlidingWindowWidth
        {
            get
            {
                return ((int)(this["SlidingWindowWidth"]));
            }
            set
            {
                this["SlidingWindowWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2560")]
        public int SlidingWindowHeight
        {
            get
            {
                return ((int)(this["SlidingWindowHeight"]));
            }
            set
            {
                this["SlidingWindowHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int SlidingOverlapX
        {
            get
            {
                return ((int)(this["SlidingOverlapX"]));
            }
            set
            {
                this["SlidingOverlapX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int SlidingOverlapY
        {
            get
            {
                return ((int)(this["SlidingOverlapY"]));
            }
            set
            {
                this["SlidingOverlapY"] = value;
            }
        }
    }
}
