//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成�?
//     运行时版�? 4.0.30319.42000
//
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace DlcvTest.Properties
{


    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等�?
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似�?ResGen �?Visual Studio 的工具自动生成的�?
    // 若要添加或移除成员，请编�?.ResX 文件，然后重新运�?ResGen
    // (�?/str 作为命令选项)，或重新生成 VS 项目�?
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   返回此类使用的缓�?ResourceManager 实例�?
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DlcvTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程�?CurrentUICulture 属性，�?
        ///   使用此强类型资源类的所有资源查找执行重写�?
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}

